name: CI Java

on:
  workflow_call:

jobs: 

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3.5.3
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3.12.0
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Compile Gradle
      run: |
        chmod +x gradlew
        ./gradlew build 

    - name: Analisis SonarCloud
      run: |
        chmod +x gradlew
        ./gradlew sonar -Dsonar.token=${{ secrets.TOKEN_SONARCLOUD }}

    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
